wode_fenxiang 用例运行失败,请检查！
Traceback (most recent call last):
  File "po\ExcuteCase.py", line 22, in wrapper
    func(*args, **kwargs)
  File "d:\python27\lib\site-packages\allure\common.py", line 62, in impl
    return func(*a, **kw)
  File "D:\lzm-demo\ui_auto\testcase\test_019_wode_fenxiang.py", line 28, in wode_fenxiang
    d(resourceId="com.chinamobile.cloudapp:id/invitation_reward_record_btn").click()
  File "D:\Python27\lib\site-packages\uiautomator2\__init__.py", line 1425, in inner
    'message': E(self.selector.__str__())
UiObjectNotFoundError: -32002 Server error: <Selector [resourceId=u'com.chinamobile.cloudapp:id/invitation_reward_record_btn']> data: 

